package: yform_dropzone
version: 0.7.1-dev
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/yform_dropzone

pages:
    yform/dropzone: 
        title: dropzone
        path: pages/index.php
        subPath: README.md
        perm: admin


requires:
    redaxo: ^5.7.0
    yform: ^3.0
    php:
        version: ^7.0
