package: yform_dropzone
version: 0.7-dev
author: Alexander Walther, Paul Götz, Thoams Skerbis
supportpage: https://github.com/skerbis/yform_dropzone/

pages:
    yform/dropzone:
        title: dropzone.js
        perm: admin


requires:
    redaxo: ^5.7.0
    yform: ^3.0