package: yuploader
version: dev
author: Alexander Walther, Paul Götz, Thoams Skerbis
supportpage: https://github.com/skerbis/yuploader/

pages:
    yform/dropzone:
        title: dropzone.js
        perm: admin


requires:
    redaxo: ^5.7.0-beta2
    yform: ^3.0